export * from './articleControllerService.service';
import { ArticleControllerServiceService } from './articleControllerService.service';
export * from './articleImageControllerService.service';
import { ArticleImageControllerServiceService } from './articleImageControllerService.service';
export * from './bloggerControllerService.service';
import { BloggerControllerServiceService } from './bloggerControllerService.service';
export * from './categoryControllerService.service';
import { CategoryControllerServiceService } from './categoryControllerService.service';
export * from './channelControllerService.service';
import { ChannelControllerServiceService } from './channelControllerService.service';
export * from './commentControllerService.service';
import { CommentControllerServiceService } from './commentControllerService.service';
export * from './companyControllerService.service';
import { CompanyControllerServiceService } from './companyControllerService.service';
export * from './companyTypeControllerService.service';
import { CompanyTypeControllerServiceService } from './companyTypeControllerService.service';
export * from './groupControllerService.service';
import { GroupControllerServiceService } from './groupControllerService.service';
export * from './inventoryControllerService.service';
import { InventoryControllerServiceService } from './inventoryControllerService.service';
export * from './inventoryImageControllerService.service';
import { InventoryImageControllerServiceService } from './inventoryImageControllerService.service';
export * from './moduleControllerService.service';
import { ModuleControllerServiceService } from './moduleControllerService.service';
export * from './paymentControllerService.service';
import { PaymentControllerServiceService } from './paymentControllerService.service';
export * from './productFeatureControllerService.service';
import { ProductFeatureControllerServiceService } from './productFeatureControllerService.service';
export * from './productPromotionControllerService.service';
import { ProductPromotionControllerServiceService } from './productPromotionControllerService.service';
export * from './productReviewControllerService.service';
import { ProductReviewControllerServiceService } from './productReviewControllerService.service';
export * from './roleControllerService.service';
import { RoleControllerServiceService } from './roleControllerService.service';
export * from './saleControllerService.service';
import { SaleControllerServiceService } from './saleControllerService.service';
export * from './shippingControllerService.service';
import { ShippingControllerServiceService } from './shippingControllerService.service';
export * from './storeControllerService.service';
import { StoreControllerServiceService } from './storeControllerService.service';
export * from './storeReviewControllerService.service';
import { StoreReviewControllerServiceService } from './storeReviewControllerService.service';
export * from './ticketControllerService.service';
import { TicketControllerServiceService } from './ticketControllerService.service';
export * from './typeControllerService.service';
import { TypeControllerServiceService } from './typeControllerService.service';
export * from './userControllerService.service';
import { UserControllerServiceService } from './userControllerService.service';
export * from './verificationCodeControllerService.service';
import { VerificationCodeControllerServiceService } from './verificationCodeControllerService.service';
export * from './videoControllerService.service';
import { VideoControllerServiceService } from './videoControllerService.service';
export * from './voucherCodeControllerService.service';
import { VoucherCodeControllerServiceService } from './voucherCodeControllerService.service';
export * from './voucherControllerService.service';
import { VoucherControllerServiceService } from './voucherControllerService.service';
export * from './warrantyControllerService.service';
import { WarrantyControllerServiceService } from './warrantyControllerService.service';
export const APIS = [ArticleControllerServiceService, ArticleImageControllerServiceService, BloggerControllerServiceService, CategoryControllerServiceService, ChannelControllerServiceService, CommentControllerServiceService, CompanyControllerServiceService, CompanyTypeControllerServiceService, GroupControllerServiceService, InventoryControllerServiceService, InventoryImageControllerServiceService, ModuleControllerServiceService, PaymentControllerServiceService, ProductFeatureControllerServiceService, ProductPromotionControllerServiceService, ProductReviewControllerServiceService, RoleControllerServiceService, SaleControllerServiceService, ShippingControllerServiceService, StoreControllerServiceService, StoreReviewControllerServiceService, TicketControllerServiceService, TypeControllerServiceService, UserControllerServiceService, VerificationCodeControllerServiceService, VideoControllerServiceService, VoucherCodeControllerServiceService, VoucherControllerServiceService, WarrantyControllerServiceService];
