/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Blogger } from './blogger';
import { Comment } from './comment';
import { ArticleImage } from './articleImage';


export interface Article { 
    id?: number;
    blogger_id?: number;
    uid?: string;
    title?: string;
    desc?: string;
    view?: number;
    like?: number;
    dislike?: number;
    scope?: string;
    agerestrict?: number;
    status?: number;
    created_at?: string;
    updated_at?: string;
    commentcount?: number;
    articleimages?: Array<ArticleImage>;
    store?: Blogger;
    comments?: Array<Comment>;
}

