/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Company { 
    id?: number;
    company_type_id?: number;
    uid?: string;
    name?: string;
    img?: string;
    regno?: string;
    tel1?: string;
    tel2?: string;
    fax1?: string;
    fax2?: string;
    email1?: string;
    email2?: string;
    address1?: string;
    address2?: string;
    postcode?: string;
    city?: string;
    state?: string;
    country?: string;
    status?: number;
    created_at?: string;
    updated_at?: string;
}

