/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductFeature { 
    id?: number;
    uid?: string;
    name?: string;
    icon?: string;
    imgpath?: string;
    imgpublicid?: string;
    desc?: string;
    status?: number;
    created_at?: string;
    updated_at?: string;
}

