/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductPromotion { 
    id?: number;
    uid?: string;
    store_id?: number;
    name?: string;
    desc?: string;
    qty?: number;
    disc?: number;
    discpctg?: number;
    discbyprice?: number;
    promostartdate?: string;
    promoenddate?: string;
    status?: number;
    created_at?: string;
    updated_at?: string;
}

