/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaleItem } from './saleItem';
import { User } from './user';
import { Store } from './store';


export interface Sale { 
    id?: number;
    user_id?: number;
    store_id?: number;
    voucher_id?: number;
    uid?: string;
    sono?: string;
    email?: string;
    contact?: string;
    qty?: number;
    disc?: number;
    totalcost?: number;
    totalprice?: number;
    charge?: number;
    net?: number;
    grandtotal?: number;
    salestatus?: string;
    status?: string;
    remark?: string;
    pos?: number;
    created_at?: string;
    updated_at?: string;
    user?: User;
    saleitems?: Array<SaleItem>;
    store?: Store;
}

