/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    uid?: string;
    name?: string;
    email?: string;
    icno?: string;
    tel1?: string;
    tel2?: string;
    address1?: string;
    address2?: string;
    postcode?: string;
    city?: string;
    state?: string;
    country?: string;
    password?: string;
    status?: string;
    last_login?: string;
    last_active?: string;
    remember_token?: string;
    created_at?: string;
    updated_at?: string;
}

