/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Channel } from './channel';


export interface Video { 
    id?: number;
    channel_id?: number;
    playlist_id?: number;
    uid?: string;
    title?: string;
    desc?: string;
    videopath?: string;
    videopublicid?: string;
    imgpath?: string;
    imgpublicid?: string;
    totallength?: string;
    view?: number;
    like?: number;
    dislike?: number;
    price?: number;
    discpctg?: number;
    disc?: number;
    discbyprice?: number;
    free?: number;
    salesqty?: number;
    scope?: string;
    agerestrict?: number;
    status?: number;
    created_at?: string;
    updated_at?: string;
    commentcount?: number;
    channel?: Channel;
}

